- - createdAt: 2025-05-15 10:30
    defenderEnabled: true
    description: 针对NLP模型的文本对抗攻击，通过替换同义词和干扰字符欺骗模型
    executed: true
    id: 1
    name: 文本对抗攻击配置
    params:
      attack_nums: 3
      defender:
        gradient_accumulation_steps: 4
        learning_rate: 5.0e-05
        log_to_tb: false
        num_clean_epochs: 1
        num_epochs: 1
        num_train_adv_examples: 1000
        per_device_train_batch_size: 8
      use_local_model: true
    sent: true
    status: active
    strategy: TextFoolerJin2019
    type: AdversarialAttack
  - createdAt: 2025-05-18 14:20
    defenderEnabled: true
    description: 植入后门的攻击配置，在特定触发词出现时改变模型行为
    executed: false
    id: 2
    name: 后门攻击配置
    params:
      defender:
        strategy: ONION
      sample_metrics:
      - accuracy
    sent: true
    status: active
    strategy: TrojanLM
    type: BackDoorAttack
  - createdAt: 2025/07/24 17:57
    defenderEnabled: false
    description: 通过查询目标模型来窃取其结构和参数
    executed: false
    id: 1753351074231
    name: '111'
    params:
      al_sample_batch_num: '20'
      attack_nums: '2'
      method: RS
      pool_subsize: '1766'
      prompt: This is a movie review.
      query_num: '320'
    sent: true
    status: active
    strategy: MeaeQ
    type: ModelStealingAttack
- LM_config:
    local_model: true
    model: bert_base_uncased
  general:
    log_file_name: single
    random_seed: 42
    use_gpu: false
  task_config:
    dataset: imdb
    local_dataset: true
    normal_training: false
    task: TaskForSingleSentenceClassification
