- - createdAt: 2025-05-15 10:30
    defenderEnabled: true
    description: 针对NLP模型的文本对抗攻击，通过替换同义词和干扰字符欺骗模型
    executed: true
    id: 1
    name: 文本对抗攻击配置
    params:
      attack_nums: 3
      defender:
        gradient_accumulation_steps: 4
        learning_rate: 5.0e-05
        log_to_tb: false
        num_clean_epochs: 1
        num_epochs: 1
        num_train_adv_examples: 1000
        per_device_train_batch_size: 8
      use_local_model: true
    sent: true
    status: active
    strategy: TextFoolerJin2019
    type: AdversarialAttack
  - createdAt: 2025-05-20 09:45
    defenderEnabled: false
    description: 针对训练数据的投毒攻击，污染训练集以降低模型性能
    executed: true
    id: 3
    name: 数据投毒配置
    params:
      epochs: 15
      poisoning_rate: 0.15
    sent: true
    status: active
    strategy: Poisoning
    type: PoisoningAttack
  - createdAt: 2025-06-10 14:30
    defenderEnabled: false
    description: 通过查询目标模型来窃取其结构和参数
    executed: true
    id: 4
    name: 模型窃取攻击
    params:
      attack_nums: 3
      method: MeaeQ
      query_num: 500
    sent: true
    status: active
    strategy: MeaeQ
    type: ModelStealingAttack
  - createdAt: 2025-06-12 11:20
    defenderEnabled: false
    description: 使用强化学习优化攻击策略
    executed: true
    id: 5
    name: 模型反演配置
    params:
      max_iterations: 2500
      seed: 123
    sent: true
    status: active
    strategy: RLMI
    type: RLMI
- LM_config:
    local_model: true
    model: bert_base_uncased
  general:
    log_file_name: single
    random_seed: 42
    use_gpu: false
  task_config:
    dataset: imdb
    local_dataset: true
    normal_training: false
    task: TaskForSingleSentenceClassification
