- - createdAt: 2025-07-15 10:30
    defenderEnabled: true
    description: 针对NLP模型的文本对抗攻击，通过替换同义词和干扰字符欺骗模型
    id: 1
    name: 对抗攻击-1（防御）
    params:
      attack_nums: 3
      defender:
        gradient_accumulation_steps: 4
        learning_rate: 5.0e-05
        log_to_tb: false
        num_clean_epochs: 0
        num_epochs: 1
        num_train_adv_examples: 10
        per_device_train_batch_size: 8
    strategy: TextFoolerJin2019
    type: AdvAttack
- null
